phantomJar:
  consumeMessages:
    - "Tastes like the essence of... something unsettling."
    - "I didn't think capturing a soul would taste this weird."
    - "Is it just me, or does this taste a little too lively?"
    - "I thought bottled souls would be... fresher?"
    - "Hmm… I didn’t know a {entity} soul would taste like lemonade!"
    - "It’s like drinking someone’s last breath. Yum?"
    - "I guess that's what a {entity} soul tastes like… Not great."
    - "Well, that’s one way to bottle a spirit!"
    - "Why would anyone even drink a soul?!"
    - "That’s one angry {entity} soul in there… probably shouldn’t drink it."
    - "Feels like I’m drinking someone’s unfinished business."
    - "This is more like ghost juice, not my cup of tea."
    - "It’s like a taste of haunting memories… maybe I shouldn’t have done that."
    - "Whatever soul this was, it sure had a strong aftertaste!"
    - "This must be what regret tastes like... bottled and all."
    - "Mmm… soul smoothie. Not bad!"
    - "Was that... a little bit of soul in my drink?"
    - "I wonder if souls are supposed to taste like this…"
    - "This tastes like eternal regret... with a hint of despair."
    - "Not sure if I’m drinking a soul or a bad decision."
    - "Wow, this {entity} had a spicy afterlife!"
    - "I thought souls would taste more... ethereal."
    - "This is definitely not what I signed up for."
    - "Drinking a soul? Sure. What could possibly go wrong?"
    - "Yikes! That’s one angry {entity}... probably shouldn't do that again."
    - "I can feel the soul wriggling inside… weird."
    - "Was that... a scream I just drank?"
    - "I think I just tasted... regret."
    - "Drinking a soul... because why not, right?"
    - "It’s like the taste of unfinished business... bottled."
    - "Well, it’s official. Souls taste worse than I thought."
    - "I can taste the torment in every sip!"
    - "This is some seriously dark lemonade."
    - "It’s like I’m drinking bottled nightmares."
    - "Definitely not the taste of victory…"
    - "Next time, I’ll stick to potions."
    - "This is what haunted dreams must taste like."
    - "Yup, that was definitely a soul... with a side of dread."
    - "It’s like drinking pure chaos... in a bottle."
    - "I think I just swallowed a grudge."
    - "This {entity} soul is giving me indigestion."
    - "It feels like a thousand years of bad decisions in one gulp."
    - "Did I just drink someone's last regret?"
    - "This might be the most disturbing drink I’ve ever had."
    - "Is this what a bottled conscience tastes like?"
    - "That was a soul? Could’ve fooled me!"
    - "It’s like drinking a cloud of misery… refreshing."
    - "Soul juice... not as sweet as I expected."
    - "That’s going to haunt me for a while."
    - "I feel like I just drank a ghost’s bad day."
  blacklistEntities:
    - ENDER_DRAGON
    - WITHER
    - ILLUSIONER
    - ELDER_GUARDIAN
    - WARDEN
